name = "FEsolver"
version = "0.1.0"
license = "license"
author = "yaungcn"
maintainer = "yaungcn@outlook.com"
copyright = "Copyright 2023, yaungcn"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["openblas"]
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
